import { useEffect, useLayoutEffect, useRef, useState } from "react";
import { IoIosArrowDown } from "react-icons/io";

import type { NextPage } from "next";
import Head from "next/head";
import { gsap, Power3 } from "gsap";
import ScrollTrigger from "gsap/dist/ScrollTrigger";
import Button from "./components/Inputs/button";
import SocialIcon from "./components/socialIcons";
import ChatBubble from "./components/chatBubble";

import Header from "./components/header";
import Footer from "./components/footer";
import gsapActions from "./hooks/gsapActions";
import { useInView } from "react-intersection-observer";
import Newake from "./components/text/newake";
import JosefinSans from "./components/text/josefinSans";
import ProductCard from "./components/productCart";
import Benefits from "./components/benefits";
import Twitter from "./components/socialButtons/twitter";
const Home: NextPage = () => {
  const boxRef = useRef<any>();
  const marqueeText = useRef<any>();

  const { bgTimeLine, graphicScroll, shape2, marquee } = gsapActions(boxRef);
  gsap.registerPlugin(ScrollTrigger);
  const [showMore, setShowMore] = useState(false);
  const { ref, inView, entry } = useInView({
    threshold: 0,
  });

  useEffect(() => {
    bgTimeLine();
    graphicScroll();
    shape2();
    marquee(marqueeText);
    return () => {
      bgTimeLine();
      graphicScroll();
      shape2();
    };
  }, []);

  useEffect(() => {}, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className=" mx-auto overflow-hidden mainScrollScreen wrap "
        ref={boxRef}
      >
        <div className="overlayPattern">
          <Header showLogo={inView} />
          <div className="screen1 section relative">
            <div className="logo mt-10 z-30 relative flex justify-center">
              <img src="images/mainLogo.png" />
            </div>
            <img
              src="images/vectorBg.svg"
              className="absolute z-0 top-10 bottom-auto"
            />
            <Newake tag="h4">MINT AVAILABLE Q3 2022</Newake>
            <Button text={"CONNECT WALLET"} />

            <Newake tag="h4"> JOIN OUR COMMUNITY</Newake>

            <div className="flex justify-center mt-3">
              <SocialIcon>
                <img src="images/instagram_white.png" className="" />
              </SocialIcon>
              <SocialIcon>
                <img src="images/discord_white.png" />
              </SocialIcon>
              <SocialIcon>
                <img src="images/twitter_white.png" />
              </SocialIcon>
            </div>
          </div>
          <div className="screen2 section">
            <div className="w-full py-12 relative text-center">
              <img
                src="images/bottleRight.png"
                className="absolute right-0 top-0"
              />

              <Newake tag="h4" size="lg" color="yellowColor">
                OUR STORY
              </Newake>

              <Newake
                tag="h2"
                size="2xl"
                color="white"
                padding="px-2"
                margin="mt-5 mb-20"
                textTransform="uppercase"
              >
                Ojo de Dios is the eye to the soul of Mexico, a MASTER award
                winning Mezcal from Oaxaca Mexico. <br />
                <br />
                The OddSquad is the world’s first NFT-powered members club for
                mezcal lovers, coming 2022.{" "}
              </Newake>
              <img
                src="images/bottleLeft.png"
                className="absolute left-0 bottom-0"
              />
            </div>
          </div>
          <div className="relative h-full">
            <div className="screen3  z-10 relative section">
              <div className="w-full py-12 relative text-center group ">
                <ChatBubble align="left" message={"Hola!"} left={2} />
                <ChatBubble
                  align="right"
                  message={
                    "I’m Oddball, leader of the OddSquad and your spirit guide to all that is Ojo de Dios, mezcal and Mexico."
                  }
                  left={3}
                />
                <ChatBubble
                  align="left"
                  message={
                    "I’m here to ask you for your help on my quest for the 4 elements..."
                  }
                  left={1}
                />
                <ChatBubble align="right" message={"Care to join?"} left={5} />

                <img
                  src="images/graphicCharacter.png"
                  className="absolute z-0 -bottom-9"
                />
              </div>
            </div>
            <img
              src="images/bgShape1.png"
              id="shape1"
              className="absolute bgShape1 z-0 ml-40 "
            />
            <div className="screen4 py-40 z-10 relative section">
              <div className="bg-gray-900 bg-opacity-0.3 border flex justify-center items-center border-white border-2   h-60  w-10/12 m-auto rounded-2xl h-32 relative">
                <div className="ml-24 top-auto bottom-auto flex  items-center">
                  <div className="icon">
                    <img src="images/playButton.svg" className="" />
                  </div>
                  <div className="text-left">
                    <Newake
                      margin="mt-0 ml-2"
                      align="text-left"
                      size="sm"
                      tag="h4"
                    >
                      PLAY OUR FILM
                    </Newake>
                  </div>
                </div>
              </div>

              <div className="bg-black bg-opacity-0.3   px-7 py-5  my-5  h-60  w-10/12 m-auto rounded-2xl  relative">
                <div className="flex  flex-row flex-1 align-top">
                  <img src="images/book-open.svg" className="w-5 h-5" />
                  <div className="h-5">
                    <Newake
                      width="w-5/12"
                      margin="mt-0 ml-2"
                      align="text-left"
                      size="sm"
                      tag="h4"
                      color="yellowColor1"
                    >
                      THE QUEST FOR THE 4 ELEMENTS
                    </Newake>

                    <Newake
                      width="w-12/12"
                      margin="mt-5 ml-2"
                      align="text-left"
                      size="sm"
                      tag="h4"
                      color="white"
                      weight="font-normal"
                    >
                      Spirit Guides are intermediaries between spiritual and
                      human spheres provided by the gods for shaman
                      apprentices...
                    </Newake>

                    <div className="mt-5">
                      <div
                        className="cursor-pointer p-0 m-0 ml-2  flex items-center  text-white"
                        onClick={() => setShowMore(true)}
                      >
                        <IoIosArrowDown />
                        <JosefinSans
                          tag="h4"
                          color="white"
                          opacity="text-opacity-50"
                          size="xs"
                          weight="font-bold"
                          textTransform="uppercase"
                          margin="m-0 ml-2"
                        >
                          READ MORE
                        </JosefinSans>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="screen5 z-10 relative section">
            <img
              src="images/bgGraphic2.svg"
              id="shape2"
              className="absolute z-0 -ml-40 "
            />
            <Newake tag="h4" size="lg" color="yellowColor">
              OUR STORY
            </Newake>
            <div
              className="marquee w-full -z-10 overflow-hidden whitespace-nowrap "
              id="no01"
              ref={marqueeText}
            >
              <JosefinSans
                tag="h4"
                color="white"
                size="5xl"
                width="w-auto"
                className={"marqueeText"}
                weight="font-extrabold	"
                textTransform="uppercase"
                margin="mt-0"
              >
                JOIN THE SQUAD
              </JosefinSans>
              <JosefinSans
                tag="h4"
                color="white"
                width="w-auto"
                size="5xl"
                className={"marqueeText"}
                weight="font-extrabold	"
                textTransform="uppercase"
                margin="mt-0"
              >
                JOIN THE SQUAD
              </JosefinSans>
            </div>

            <ProductCard />
            <div className="text-center  flex justify-center relative">
              <img
                src="images/logoText.png"
                className="absolute -z-10 -top-2"
              />
              <div className="text-center">
                <h3 className="text-white w-auto text-4xl font-Newake font-extrabold uppercase mt-28 z-10">
                  Member&apos;s Pass
                </h3>

                <h2 className="text-white w-auto text-8xl	 font-Newake font-semibold mt-2 uppercase  z-10">
                  3,333
                </h2>
                <p className="text-4xl my-6 font-Newake px-4 text-white text-center ">
                  We’re opening the books to our coveted member’s club. Join the
                  ODDSquad as an OG member to ensure you always get the best
                  perks on offer.
                </p>

                <p className="text-4xl my-6 font-Newake px-4 text-white text-center ">
                  Journey with us into our Odd World for In-Real-Life
                  experiences, limited editions, exclusive parties and tones of
                  Web3 goodies. The OddSquad Member’s Pass will be your ticket
                  to ride.
                </p>
              </div>
              <div className="clear-both"></div>
            </div>
          </div>
          <div className="screen6 z-10 h-screen relative section">
            <Newake tag="h4" margin="mb-4" size="lg" color="yellowColor">
              OG MEMBER BENEFITS
            </Newake>
            <div className="">
              <Benefits>
                Free OddSquad <br /> profile pictures
              </Benefits>
              <Benefits>
                Exclusive invites to IRL events
                <br /> and VIP access
              </Benefits>
              <Benefits>
                Collaborations with top Mexican <br /> Artists, airdropped to
                holders
              </Benefits>
              <Benefits>
                Free bottles of mezcal* <br /> and merch drops
                <h4 className="opacity-60 font-Newake font-light text-xs">
                  *legal stipulations apply
                </h4>
              </Benefits>
              <Benefits>
                Access to one off Limited Edition
                <br /> bottles of Ojo de Dios Mezcal
              </Benefits>
              <Benefits>
                Be part of the first Metaverse
                <br /> community for mezcal lovers
              </Benefits>
            </div>
          </div>

          <div className="screen6 z-10 h-screen relative section">
            <Newake tag="h4" margin="mb-4" size="lg" color="yellowColor">
              JOIN THE QUEST
            </Newake>

            <div className="flex justify-between flex-col h-3/5">
              <p className="text-4xl my-6 font-Newake px-4 text-white text-center ">
                Follow us for a whitelist spot and join the whitelist spot
              </p>
              <Twitter />
            </div>
          </div>
          {inView && <Footer />}
        </div>
        {/* <div className="panel w-full sec1">
          <h1 className="w-full	">asd</h1>
        </div>
        <div className="panel w-full	">
          <h1 className="w-full	">asd</h1>
        </div>
        <div className="panel w-full	sec2">
          <h1 className="w-full	">asd</h1>
        </div>
        <div className="panel w-full	sec3">
          <h1 className="w-full	">asd</h1>
        </div>
        <div className="panel w-full sec3	">
          <h1 className="w-full	">asd</h1>
        </div> */}
      </div>
    </div>
  );
};

export default Home;
