import { useEffect, useRef, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { gsap } from "gsap";
import ScrollTrigger from "gsap/dist/ScrollTrigger";
import Button from "./components/Inputs/button";
import SocialIcon from "./components/socialIcons";
import Header from "./components/header";
import { useInView } from "react-intersection-observer";

const Home: NextPage = () => {
  const boxRef = useRef<any>();
  gsap.registerPlugin(ScrollTrigger);
  const child = gsap.utils.selector(boxRef);
  const tl = gsap.timeline();
  const { ref, inView, entry } = useInView({
    /* Optional options */
    threshold: 0,
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" mx-auto mainScrollScreen " ref={boxRef}>
        <div className="overlayPattern">
          <Header showLogo={inView} />
          <div className="screen1 ">
            <div className="logo mt-10 flex justify-center">
              <img src="images/mainLogo.png" />
            </div>

            <h4 className="font-Newake text-sm text-center uppercase mt-10 text-white">
              MINT AVAILABLE Q3 2022
            </h4>
            <Button text={"CONNECT WALLET"} />

            <h4 className="font-Newake text-sm text-center uppercase mt-10 text-white">
              JOIN OUR COMMUNITY
            </h4>

            <div className="flex justify-center mt-3">
              <SocialIcon>
                <img src="images/instagram_white.png" className="" />
              </SocialIcon>
              <SocialIcon>
                <img src="images/discord_white.png" />
              </SocialIcon>
              <SocialIcon>
                <img src="images/twitter_white.png" />
              </SocialIcon>
            </div>
          </div>

          <div className="screen2 " ref={ref}>
            <h4 className="font-Newake text-sm text-center uppercase mt-10 text-white">
              MINT AVAILABLE Q3 2022
            </h4>
            <Button text={"CONNECT WALLET"} />

            <h4 className="font-Newake text-sm text-center uppercase mt-10 text-white">
              JOIN OUR COMMUNITY
            </h4>

            <div className="flex justify-center mt-3">
              <SocialIcon>
                <img src="images/instagram_white.png" className="" />
              </SocialIcon>
              <SocialIcon>
                <img src="images/discord_white.png" />
              </SocialIcon>
              <SocialIcon>
                <img src="images/twitter_white.png" />
              </SocialIcon>
            </div>
          </div>
        </div>
        {/* <div className="panel w-full sec1">
          <h1 className="w-full	">asd</h1>
        </div>
        <div className="panel w-full	">
          <h1 className="w-full	">asd</h1>
        </div>
        <div className="panel w-full	sec2">
          <h1 className="w-full	">asd</h1>
        </div>
        <div className="panel w-full	sec3">
          <h1 className="w-full	">asd</h1>
        </div>
        <div className="panel w-full sec3	">
          <h1 className="w-full	">asd</h1>
        </div> */}
      </div>
    </div>
  );
};

export default Home;
